### ISSUE TITLE
Use hpcc.jar for queries from i2b2

### ISSUE THREAD

**Issue by mpbismar** [bp2014n2/i2b2#109]
- [x] build and deploy jBoss with hpcc.jar as QueryToolDemoDS (datasource)
- [x] adapt the hpcc-jdbc driver to usage of it in CRC cell
- [x] correctly receive results from hpcc in i2b2
- [x] eradicate remaining errors through debugging

**Comment by philipp94831** [comment]
Duplicates #85 ;)
