### ISSUE TITLE
Node error in citusdb

### ISSUE THREAD

**Issue by arunnairmr** [bp2014n2/i2b2#128]
I am getting a node error when tiring to create a shard.

SELECT * from master_create_empty_shard('customer_reviews');
Error: could only find 0 of 2 possible nodes error in citusdb

same error was getting for the following also.

\STAGE customer_reviews FROM '/home/ubuntu/customer_reviews_1998.csv' (FORMAT CSV)

**Comment by CarlAmbroselli** [comment]
I think you created the issue in the wrong repository!
