### ISSUE TITLE
Handle temp tables

### ISSUE THREAD

**Issue by SvenLehmann** [bp2014n2/i2b2#154]
HPCC does not implement temp tables. However  I2B2 uses that type of query when querying PostgreSQL.

There are different possibilities to map that on HPCC:
- model temp tables by tables with an unique session key (PostgreSQL approach)
- create an ECL object tree in order to collect multiple queries from `create temp table` to `drop table`

**Comment by philipp94831** [comment]
**TEMPORARY or TEMP**
> If specified, the table is created as a temporary table. Temporary tables are automatically dropped at the end of a session, or optionally at the end of the current transaction (see ON COMMIT below). Existing permanent tables with the same name are not visible to the current session while the temporary table exists, unless they are referenced with schema-qualified names. Any indexes created on a temporary table are automatically temporary as well.
>
> The autovacuum daemon cannot access and therefore cannot vacuum or analyze temporary tables. For this reason, appropriate vacuum and analyze operations > should be performed via session SQL commands. For example, if a temporary table is going to be used in complex queries, it is wise to run ANALYZE on the > temporary table after it is populated.
>
> Optionally, GLOBAL or LOCAL can be written before TEMPORARY or TEMP. This presently makes no difference in PostgreSQL and is deprecated; see Compatibility.

[Source](http://www.postgresql.org/docs/9.2/static/sql-createtable.html)
