### ISSUE TITLE
results tab heading in girix plugin

### ISSUE THREAD

**Issue by Saulus** [bp2014n2/i2b2#181]
Results tab correctly shows results from last executed script. The heading, however, refers to the latest template that has been selected in configuration tab.

-> falsch :-)

**Comment by philipp94831** [comment]
@Saulus We can't reproduce this bug

**Comment by Saulus** [comment]
I can (almost). Behavior has changed since yesterday: Instead of a wrong heading, now no heading is shown.
See 2 screenshots from yesterday and today, both PSM-results. 
Browser: Firefox

![screen_05-06](https://cloud.githubusercontent.com/assets/4431024/7513540/3d607bf6-f4b5-11e4-950d-71a5177e6b57.PNG)
![screen_05-07](https://cloud.githubusercontent.com/assets/4431024/7513544/4178a3a8-f4b5-11e4-8f67-341ed1f55cad.PNG)

**Comment by philipp94831** [comment]
@Saulus What exactly did you do?

**Comment by Saulus** [comment]
- Started Propensity Score Matching
- got bored waiting for result
- went back to configuration tab
- selected another script, e.g. risk prediction
- took some time to review those input fields
- back to result tab to check - e voila


Von: Philipp Schirmer [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. Mai 2015 13:39
An: bp2014n2/i2b2
Cc: Hellwig, Paul (ELS-BER)
Betreff: Re: [i2b2] results tab heading in girix plugin (#181)


@Saulus<https://github.com/Saulus> What exactly did you do?

—
Reply to this email directly or view it on GitHub<https://github.com/bp2014n2/i2b2/issues/181#issuecomment-99829048>.

________________________________

Elsevier GmbH, Hackerbrücke 6, 80335 München | www.elsevier.de
Tel. +49|89|5383-0 | Fax +49|89|5383-939 | Registergericht: Amtsgericht München, HRB 152680
Geschäftsführung: Olaf Lodbrok, Martin Beck | USt.-ID. DE 180607607
