### ISSUE TITLE
"Find Terms"-Suche ermöglichen

### ISSUE THREAD

**Issue by SvenLehmann** [bp2014n2/i2b2#38]
- [ ] Fehler beheben, durch eigenen Fix oder neuen Webclient

**Comment by philipp94831** [comment]
Works with demo data

**Comment by PeterSchwarzHPI** [comment]
for code search use insert_basecodes.sql (inserts the used basecodes into eva_meta)

for text search make sure that in i2b2metadata.table_access the c_table_cd is unique (you can use the new Ontology.sql and Stammdaten.sql to do so)
